from typing import DefaultDict

from collections import defaultdict

def def_value():
    return 0

def MaxMers(seq,k):
    dct=defaultdict(def_value)
    for i in range(0,len(seq)-k+1):
        dct[seq[i:int(i+k)]]+=1

    mx = max(dct.values())
    lst = [k for k,v in dct.items() if (v) == mx]
    lst.sort()
    return " ".join(lst)

if __name__ == "__main__":
    dct={ 
    "CGGAGGACTCTAGGTAACGCTTATCAGGTCCATAGGACATTCA":3,
    "ACGTTGCATGTCGCATGATGCATGAGAGCT":4,
    "ATACAATTACAGTCTGGAACCGGATGAACTGGCCGCAGGTTAACAACAGAGTTGCCAGGCACTGCCGCTGACCAGCAACAACAACAATGACTTTGACGCGAAGGGGATGGCATGAGCGAACTGATCGTCAGCCGTCAGCAACGAGTATTGTTGCTGACCCTTAACAATCCCGCCGCACGTAATGCGCTAACTAATGCCCTGCTG":5,
    "CCAGCGGGGGTTGATGCTCTGGGGGTCACAAGATTGCATTTTTATGGGGTTGCAAAAATGTTTTTTACGGCAGATTCATTTAAAATGCCCACTGGCTGGAGACATAGCCCGGATGCGCGTCTTTTACAACGTATTGCGGGGTAAAATCGTAGATGTTTTAAAATAGGCGTAAC":5,
    "GGCGTGGCACAAACTTGATACGGGGGCGTGGCTGATACGGGACAAACTATGAAGAATGAAGAATGAAGATGATACGGGGGCGTGGCATGAAGATGATACGGGGGACCCATATGAAGAATGAAGAGGACCCATATGAAGAACAAACTACAAACTATGAAGAATGAAGAATGAAGAATGAAGAATGAAGAGGCGTGGCGGCGTGGCGGACCCATACAAACTGGCGTGGCATGAAGAATGAAGAGGCGTGGCGGCGTGGCATGAAGAGGCGTGGCACAAACTATGAAGAGGCGTGGCATGAAGAATGAAGAACAAACTACAAACTGGACCCATACAAACTATGAAGAATGAAGAGGACCCATACAAACTATGAAGATGATACGGGTGATACGGGTGATACGGGGGACCCATTGATACGGGTGATACGGGACAAACTGGACCCATGGACCCATACAAACTGGACCCATATGAAGAGGACCCATATGAAGAGGACCCATGGACCCATGGCGTGGCGGACCCATGGACCCATATGAAGATGATACGGGATGAAGAGGACCCATGGCGTGGCGGACCCATATGAAGAGGACCCATGGCGTGGCGGCGTGGCATGAAGAATGAAGATGATACGGGTGATACGGGACAAACTACAAACTATGAAGAACAAACTATGAAGAGGCGTGGCATGAAGAACAAACTGGACCCATATGAAGAGGCGTGGCTGATACGGGACAAACTATGAAGAGGCGTGGCGGCGTGGCTGATACGGGATGAAGAGGCGTGGCTGATACGGGGGCGTGGCACAAACTACAAACTATGAAGAATGAAGAGGCGTGGCGGACCCATGGCGTGGCATGAAGAATGAAGAACAAACTGGACCCATATGAAGAGGCGTGGC":11
    }

    def test(dct):
        for key in dct:
            print(key,dct[key],MaxMers(key,dct[key]))
            
    test(dct)